### ISSUE TITLE
plugin weather delay gives error

### ISSUE THREAD

**Issue by karajdaar** [Dan-in-CA/OSPi#80]
I was seeing this error
```
Checking weather status...
Weather-base water level encountered error:
Traceback (most recent call last):
  File "/home/pi/OSPi.nov212014/plugins/weather_level_adj.py", line 85, in run
    history = history_info()
  File "/home/pi/OSPi.nov212014/plugins/weather_level_adj.py", line 320, in history_info
    'humidity': float(day_info['humidity'])
ValueError: could not convert string to float: 
```
I worked around by changing line 320 in weather_level_adj.py 
```
'humidity': float(day_info['humidity']) if day_info['humidity'].isdigit() else 0
```

Similar check could be added to other data. Cheers

**Comment by Dan-in-CA** [comment]
Cleaning up old open issues. The plugins have been move to:
https://github.com/Dan-in-CA/ospi_plugins
